# This is a basic workflow to help you get started with Actions

name: RequiredApprovals

# Controls when the workflow will run
on:
  pull_request_review: 
    types: [submitted, edited, dismissed]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: API
      uses: octokit/request-action@v2.x
      id: view_pr
      with:
        route: GET /repos/jeschu1/Bug10/pulls/${{ github.event.pull_request.number }}/requested_reviewers
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - run: "echo api: '${{ steps.view_pr.outputs.data }}'"
    - name: Reviewers
      env:
        PR: ${{ toJSON(github.event.pull_request.requested_reviewers) }}
      run: echo "$PR"
    - name: Success
      # if: ${{ (github.event.review.state == 'approved') && (contains(github.event.review.user.login, 'jeschu1')) }}
      env:
        GITHUB_CONTEXT: ${{ toJSON(github) }}
      run: echo "$GITHUB_CONTEXT"
    - name: Failure
      if: ${{ !((github.event.review.state == 'approved') && (contains(github.event.review.user.login, 'jeschu1'))) }}
      run: return -1;    
