# This is a basic workflow to help you get started with Actions

name: RequiredApprovals

# Controls when the workflow will run
on:
  pull_request_review: 
    types: [submitted, edited, dismissed]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: CLI
      run: gh pr view 1
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        ISSUE: ${{ github.event.issue.html_url }}
    - name: Success
      if: ${{ (github.event.review.state == 'approved') && (contains(github.event.review.user.login, 'jeschu1')) }}
      env:
        GITHUB_CONTEXT: ${{ toJSON(github) }}
      run: echo "$GITHUB_CONTEXT"
    - name: Failure
      if: ${{ !((github.event.review.state == 'approved') && (contains(github.event.review.user.login, 'jeschu1'))) }}
      run: return -1;    
