# This is a basic workflow to help you get started with Actions

name: RequiredApprovals

# Controls when the workflow will run
on:
  pull_request_review:
    types: [edited, submitted, dismissed]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Dump GitHub context
      if: ${{ (github.event.review.state == 'approved') && (contains(github.event.pull_request.review.user.login, 'jeschu1')) }}
      env:
        GITHUB_CONTEXT: ${{ toJSON(github) }}
      run: echo "$GITHUB_CONTEXT"
    - name: Failure
      if: ${{ (github.event.review.state == 'approved') && (contains(github.event.pull_request.review.user.login, 'jeschu1')) }}
      run: return -1;    
